### ISSUE TITLE
ты ебанутый?

### ISSUE THREAD

**Issue by alex-bul** [TimWHitee/algorithms#1]
мне потребовалось 48 часов чтоб осознать вообще что происходит

**Comment by TimWHitee** [comment]
ты пробовал спорить со всеми ? Мне помогло данное решение

**Comment by alex-bul** [comment]
да, мне было страшно. Но я это сделал

**Comment by TimWHitee** [comment]
тогда вопрос закрыт

**Comment by alex-bul** [comment]
это пиздец какой-то просто, ну сколько можно

**Comment by alex-bul** [comment]
[Интро]
Пацаны не спят, но…
Пацаны не спят, но…
Пацаны не спят, но…

[Припев]
Нет, мои пацаны не спят, у них горит душа
Также как и взгляд, she wanna take a part
